# Generated by Django 3.0.5 on 2021-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210218_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='жанр')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='уникальное имя')),
            ],
        ),
    ]
